### ISSUE TITLE
Issue during installation by composer

### ISSUE THREAD

**Issue by denar90** [himiklab/yii2-ckeditor-widget#2]
Hi, I've got issue during installation by composer

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - himiklab/yii2-ckeditor-widget 1.0.2 requires bower-asset/ckeditor dev-full/4.4.x -> no matching package found.
    - himiklab/yii2-ckeditor-widget 1.0.1 requires bower-asset/ckeditor dev-full/4.4.x -> no matching package found.
    - Installation request for himiklab/yii2-ckeditor-widget * -> satisfiable by himiklab/yii2-ckeditor-widget[1.0.1, 1.0.2].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <http://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

**Comment by himiklab** [comment]
Привет!
Что-то опять с бовером, вернул композер, попробуйте сейчас.
https://github.com/himiklab/yii2-ckeditor-widget/commit/45c89e6d94334d34636500d6c611f9cf43063141

**Comment by denar90** [comment]
Та же ерунда.

**Comment by himiklab** [comment]
Сейчас должно быть нормально, попробуйте.
https://github.com/himiklab/yii2-ckeditor-widget/commit/02127433c5cfd583f4fc00ec223c2d53df14fbbf

**Comment by denar90** [comment]
Все заработало, спасибо.
